export const moviesData = [
  { id: 1, title: "Inception", genre: "Sci-Fi", releaseYear: 2010 },
  { id: 2, title: "The Dark Knight", genre: "Action", releaseYear: 2008 },
  { id: 3, title: "Forrest Gump", genre: "Drama", releaseYear: 1994 },
  {
    id: 4,
    title: "The Shawshank Redemption",
    genre: "Drama",
    releaseYear: 1994,
  },
  { id: 5, title: "Pulp Fiction", genre: "Crime", releaseYear: 1994 },
  { id: 6, title: "The Matrix", genre: "Sci-Fi", releaseYear: 1999 },
  { id: 7, title: "Avatar", genre: "Action", releaseYear: 2009 },
  { id: 8, title: "Titanic", genre: "Romance", releaseYear: 1997 },
  { id: 9, title: "The Godfather", genre: "Crime", releaseYear: 1972 },
  {
    id: 10,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genre: "Fantasy",
    releaseYear: 2001,
  },
  { id: 11, title: "Jurassic Park", genre: "Adventure", releaseYear: 1993 },
  {
    id: 12,
    title: "Eternal Sunshine of the Spotless Mind",
    genre: "Romance",
    releaseYear: 2004,
  },
  { id: 13, title: "Gladiator", genre: "Action", releaseYear: 2000 },
  {
    id: 14,
    title: "The Silence of the Lambs",
    genre: "Thriller",
    releaseYear: 1991,
  },
  { id: 15, title: "Inglourious Basterds", genre: "War", releaseYear: 2009 },
  {
    id: 16,
    title: "The Social Network",
    genre: "Biography",
    releaseYear: 2010,
  },
  {
    id: 17,
    title: "Back to the Future",
    genre: "Adventure",
    releaseYear: 1985,
  },
  { id: 18, title: "The Lion King", genre: "Animation", releaseYear: 1994 },
  { id: 19, title: "The Shining", genre: "Horror", releaseYear: 1980 },
  { id: 20, title: "Interstellar", genre: "Sci-Fi", releaseYear: 2014 },
  { id: 21, title: "The Terminator", genre: "Sci-Fi", releaseYear: 1984 },
  { id: 22, title: "The Great Gatsby", genre: "Drama", releaseYear: 2013 },
  { id: 23, title: "Forrest Gump", genre: "Drama", releaseYear: 1994 },
  { id: 24, title: "The Green Mile", genre: "Drama", releaseYear: 1999 },
  { id: 25, title: "Fight Club", genre: "Drama", releaseYear: 1999 },
  {
    id: 26,
    title: "The Dark Knight Rises",
    genre: "Action",
    releaseYear: 2012,
  },
  { id: 27, title: "The Avengers", genre: "Action", releaseYear: 2012 },
  {
    id: 28,
    title: "The Pursuit of Happyness",
    genre: "Biography",
    releaseYear: 2006,
  },
  {
    id: 29,
    title: "The Grand Budapest Hotel",
    genre: "Comedy",
    releaseYear: 2014,
  },
  {
    id: 30,
    title: "The Wolf of Wall Street",
    genre: "Biography",
    releaseYear: 2013,
  },
  { id: 31, title: "The Martian", genre: "Adventure", releaseYear: 2015 },
  { id: 32, title: "Django Unchained", genre: "Western", releaseYear: 2012 },
  { id: 33, title: "Schindler's List", genre: "Biography", releaseYear: 1993 },
  { id: 34, title: "Inglourious Basterds", genre: "War", releaseYear: 2009 },
  { id: 35, title: "The Prestige", genre: "Drama", releaseYear: 2006 },
  { id: 36, title: "The Departed", genre: "Crime", releaseYear: 2006 },
  { id: 37, title: "The Revenant", genre: "Action", releaseYear: 2015 },
  { id: 38, title: "Mad Max: Fury Road", genre: "Action", releaseYear: 2015 },
  { id: 39, title: "Gone with the Wind", genre: "Drama", releaseYear: 1939 },
  {
    id: 40,
    title: "The Godfather: Part II",
    genre: "Crime",
    releaseYear: 1974,
  },
];
